image: maven:latest

stages:
  - build
  - test
  - package
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling the code"
    - "mvn compile"
    - echo "compile complete"


test-job:
  stage: test
  script:
    - echo "Running unit test"
    - "mvn test"

package-job:
  stage: test
  script:
    - echo "Package the code"
    - "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

deploy-job:
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass
  stage: deploy
  only:
    refs:
      - master
  script:
    - sshpass -V
    - echo "Deploying application...."
    - echo "Application successfully deployed!"
