stages:
  - test
  - deploy

test-all:
  stage: test
  except:
    - master
  script:
    - mvn clean install

test-unit:
  stage: test
  only:
    - master
  script:
    - mvn clean package
    - cp target/quizapp-0.0.1-SNAPSHOT.jar quizapp-${CI_COMMIT_SHA}.jar
  artifacts:
    name: quizapp
    expire_in: 1 week
    paths:
      - quizapp-${CI_COMMIT_SHA}.jar

deploy:
  stage: deploy
  needs: [test-unit]
  only:
    - master
  script:
    - ls quizapp-*.jar