apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: quiz-app-spring-boot
spec:
  selector:
    matchLabels:
      app: quiz-app-spring-boot
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: quiz-app-spring-boot
    spec:
      containers:
        - name: quiz-app-spring-boot
          image:  bansikah/quiz-app-spring-boot:v1.0  # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081 # The port that the container is running on in the cluster