name: Publish Release

on:
  push:
    tags:
      - 'v*'

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install cargo-credential
        run: cargo install cargo-credential
      - name: Store Cargo credentials
        run: |
          cargo credential add --registry crates.io ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Build release
        run: cargo build --release
      - name: Test release (optional)
        run: cargo test --release  # Uncomment to run tests
      - name: Publish to crates.io
        run: cargo publish --release
