name: Create Release

on:
  push:
    branches: [ master ]

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - uses: actions/checkout@v3

      - name: Create Release
        uses: actions/create-release@v1
        env:
          token: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: master
          release_name: "Feature Update (master)"
          draft: false
          prerelease: false